### ISSUE TITLE
Excpetion when loading encounters

### ISSUE THREAD

**Issue by rgwch** [rgwch/elexis-3-core#1]
```
17:03:44.047 [Worker-90] ERROR PLATFORM - [org.eclipse.core.runtime] An internal error occurred during: "Lade Konsultationen".
java.lang.ClassCastException: [B cannot be cast to java.util.List
	at ch.elexis.data.Rechnung.getInvoiceState(Rechnung.java:561) ~[na:na]
	at ch.elexis.data.Rechnung.getStatus(Rechnung.java:536) ~[na:na]
	at ch.elexis.data.Konsultation.getStatus(Konsultation.java:604) ~[na:na]
	at ch.elexis.data.Konsultation.getStatusText(Konsultation.java:626) ~[na:na]
	at ch.elexis.data.Konsultation.getLabel(Konsultation.java:635) ~[na:na]
	at ch.elexis.core.ui.actions.HistoryLoader.execute(HistoryLoader.java:170) ~[na:na]
	at ch.elexis.core.ui.actions.BackgroundJob.run(BackgroundJob.java:75) ~[na:na]
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56) ~[na:na]
```

**Comment by rgwch** [comment]
Fixed with 44ca7a7
